### ISSUE TITLE
Install PHP 7.3 with Remi repo for EL (e.g.: CentOS)

### ISSUE THREAD

**Issue by johnjelinek** [juju4/ansible-observium#1]
If I have installed PHP 7.3 with yum previously, this role fails because it wants to install old php 5 packages.

**Comment by juju4** [comment]
By design, role is using what's available in official upstream repo. can't review and test for the many alternate repositories available

https://github.com/juju4/ansible-observium/commit/a56c915658f2e1ed95fb3510d8180ddd2d9d8aa6
should give you latitude to define your own php packages
